name: TEST Merge Comment Reminders

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-merge-comment-reminders-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Input Variables
        id: configure
        run: |
          $INPUT_repository="${{ github.repository }}"
          $INPUT_issue-number="${{ github.event.pull_request.number }}"
          $INPUT_base-sha="${{ github.event.pull_request.base.sha }}"
          $INPUT_head-sha="${{ github.event.pull_request.head.sha }}"

      - name: Find merge comments
        id: find-merge-comments
        run: |
          echo "Modified files:"
          files=$(git diff --name-only $INPUT_base-sha $INPUT_head-sha)

          if [ -n "$files" ]; then
            echo "$files"
            echo ""

            echo "Modified lines:"
            lines=$(echo "$files" | xargs -r grep -r '[\/\/|#] MERGE:' || echo "")

            if [ -n "$lines" ]; then
              echo "$lines"
              echo ""

              echo "Formatting comments:"
              comments=$(echo "$lines" | sed 's/:.*[\/\/|#] MERGE/`/' | sed 's/^/- [ ] `/' )
              echo "$comments"
              echo ""

              echo 'comments<<EOF' >> $GITHUB_OUTPUT
              echo "$comments" >> $GITHUB_OUTPUT
              echo 'EOF' >> $GITHUB_OUTPUT

            else
              echo "None"
              echo "comments=None" >> "$GITHUB_OUTPUT"
            fi

          else
            echo "None"
            echo "comments=None" >> "$GITHUB_OUTPUT"
          fi

      - name: Find PR comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: $INPUT_issue-number
          comment-author: "github-actions[bot]"
          body-includes: Merge Reminders

      - name: Update PR comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: $INPUT_repository
          issue-number: $INPUT_issue-number
          edit-mode: replace
          body: |
            **Merge Reminders**
            ${{ steps.find-merge-comments.outputs.comments }}
          reactions: eyes
