name: Merge Comment Reminders

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  published-merge-comment-reminders-action:
    runs-on: ubuntu-latest

    steps:
      - name: Custom Merge Comment Reminders
        uses: pjflanagan/merge-reminders@customization
        with:
          flag: '@merge:'
          title: '@merge Custom Flag'